### ISSUE TITLE
Questions about combining sub-images

### ISSUE THREAD

**Issue by Booooooooooo** [Xiangtaokong/ClassSR#6]
Thank you for your amazing work!
I've got a little question about the way you combine the output sub-images. Due to the ill-posed nature, simply concat sub-images may cause unnatural effects. I noticed in your code that you have done the following transformation `sr_img[:,j*step*self.scale:j*step*self.scale+(patch_size-step)*self.scale,:]/=2`. What considerations led you to carry out this operation and is there any basis for it?

**Comment by Xiangtaokong** [comment]
Thank you for your attention.
Overlapping the nearest patches averaged is a common and simple operation to avoid edge artifacts caused by combining. Many works such as Path-Restore use this operation. Actually, there are many better ways to deal with edge artifacts such as overlapping the nearest patches weighted or using CNNs to learn a combining operation. 

The reason why we only use the simplest operation is:
Cropping is necessary when processing large images because of the memory limit. Edge artifacts are mainly caused
by cropping. We do not aim to explore this problem which is common and not caused by ClassSR.

**Comment by Booooooooooo** [comment]
Thank you very much for your detailed answers to my questions
